<?xml version="1.0" encoding="ASCII"?>
<ResourceModel:App xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ResourceModel="http://www.infineon.com/Davex/Resource.ecore" name="SDMMC_BLOCK" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0" description="This APP is a generic SD &amp; MMC card block device driver designed to &#xA;drive SDMMC cards with all relevant functionalities &#xA;like writing or reading blocks of data from the card." mode="NOTSHARABLE" version="4.0.26" minDaveVersion="4.1.2" instanceLabel="SDMMC_BLOCK_0" appLabel="">
  <upwardMapList xsi:type="ResourceModel:RequiredApp" href="../../FATFS/v4_0_22/FATFS_0.app#//@requiredApps.1"/>
  <properties provideInit="true"/>
  <virtualSignals name="mmc_data_out_0" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_0" hwSignal="mmc_data_out0" hwResource="//@hwResources.0"/>
  <virtualSignals name="mmc_data_out_1" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_1" hwSignal="mmc_data_out1" hwResource="//@hwResources.0"/>
  <virtualSignals name="mmc_data_out_2" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_2" hwSignal="mmc_data_out2" hwResource="//@hwResources.0"/>
  <virtualSignals name="mmc_data_out_3" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_3" hwSignal="mmc_data_out3" hwResource="//@hwResources.0"/>
  <virtualSignals name="mmc_data_out_4" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_4" hwSignal="mmc_data_out4" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_data_out_5" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_5" hwSignal="mmc_data_out5" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_data_out_6" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_6" hwSignal="mmc_data_out6" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_data_out_7" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_7" hwSignal="mmc_data_out7" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_cmd_out" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_cmd_out" hwSignal="mmc_cmd_out" hwResource="//@hwResources.0"/>
  <virtualSignals name="mmc_clk_out" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_clk_out" hwSignal="mmc_clk_out" hwResource="//@hwResources.0"/>
  <virtualSignals name="mmc_sdcd" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_sdcd" hwSignal="mmc_sdcd" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_sdwc" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_sdwc" hwSignal="mmc_sdwc" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_reset" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_rst" hwSignal="mmc_reset" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_bus_power" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_bus_pwr" hwSignal="mmc_bus_power" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mmc_led" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_led" hwSignal="mmc_led" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="data_0_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_0" hwSignal="pad" hwResource="//@hwResources.2"/>
  <virtualSignals name="data_1_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_1" hwSignal="pad" hwResource="//@hwResources.3"/>
  <virtualSignals name="data_2_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_2" hwSignal="pad" hwResource="//@hwResources.4"/>
  <virtualSignals name="data_3_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_3" hwSignal="pad" hwResource="//@hwResources.5"/>
  <virtualSignals name="data_4_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_4" hwSignal="pad" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="data_5_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_5" hwSignal="pad" hwResource="//@hwResources.7" required="false"/>
  <virtualSignals name="data_6_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_6" hwSignal="pad" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="data_7_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_7" hwSignal="pad" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="cmd_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_cmd" hwSignal="pad" hwResource="//@hwResources.10"/>
  <virtualSignals name="clk_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_clk" hwSignal="pad" hwResource="//@hwResources.11"/>
  <virtualSignals name="sdcd_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdcd" hwSignal="pad" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="sdwc_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdwc" hwSignal="pad" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="rst_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_rst" hwSignal="pad" hwResource="//@hwResources.14" required="false"/>
  <virtualSignals name="bus_pwr_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_bus_pwr" hwSignal="pad" hwResource="//@hwResources.15" required="false"/>
  <virtualSignals name="led_pad" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_led" hwSignal="pad" hwResource="//@hwResources.16" required="false"/>
  <virtualSignals name="data_0_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_0_hw_o" hwSignal="hw_o" hwResource="//@hwResources.2"/>
  <virtualSignals name="data_1_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_1_hw_o" hwSignal="hw_o" hwResource="//@hwResources.3"/>
  <virtualSignals name="data_2_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_2_hw_o" hwSignal="hw_o" hwResource="//@hwResources.4"/>
  <virtualSignals name="data_3_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_3_hw_o" hwSignal="hw_o" hwResource="//@hwResources.5"/>
  <virtualSignals name="data_4_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_4_hw_o" hwSignal="hw_o" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="data_5_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_5_hw_o" hwSignal="hw_o" hwResource="//@hwResources.7" required="false"/>
  <virtualSignals name="data_6_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_6_hw_o" hwSignal="hw_o" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="data_7_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_7_hw_o" hwSignal="hw_o" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="cmd_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_cmd_hw_o" hwSignal="hw_o" hwResource="//@hwResources.10"/>
  <virtualSignals name="clk_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_clk_hw_o" hwSignal="hw_o" hwResource="//@hwResources.11"/>
  <virtualSignals name="rst_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_rst_hw_o" hwSignal="hw_o" hwResource="//@hwResources.14" required="false"/>
  <virtualSignals name="bus_pwr_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_bus_pwr_hw_o" hwSignal="hw_o" hwResource="//@hwResources.15" required="false"/>
  <virtualSignals name="led_hw_o" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_led_hw_o" hwSignal="hw_o" hwResource="//@hwResources.16" required="false"/>
  <virtualSignals name="interrupt" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_interrupt" hwSignal="interrupt" hwResource="//@hwResources.0"/>
  <virtualSignals name="sd_host_interrupt" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_interrupt_sdmmc_host" hwSignal="signal_in" hwResource="//@hwResources.1"/>
  <virtualSignals name="Data pin 0_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_0" hwSignal="pin" hwResource="//@hwResources.17"/>
  <virtualSignals name="Data pin 1_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_1" hwSignal="pin" hwResource="//@hwResources.18"/>
  <virtualSignals name="Data pin 2_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_2" hwSignal="pin" hwResource="//@hwResources.19"/>
  <virtualSignals name="Data pin 3_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_3" hwSignal="pin" hwResource="//@hwResources.20"/>
  <virtualSignals name="Data pin 4_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_4" hwSignal="pin" hwResource="//@hwResources.21"/>
  <virtualSignals name="Data pin 5_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_5" hwSignal="pin" hwResource="//@hwResources.22"/>
  <virtualSignals name="Data pin 6_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_6" hwSignal="pin" hwResource="//@hwResources.23"/>
  <virtualSignals name="Data pin 7_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_7" hwSignal="pin" hwResource="//@hwResources.24"/>
  <virtualSignals name="Command pin_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_cmd" hwSignal="pin" hwResource="//@hwResources.25"/>
  <virtualSignals name="Clock pin_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_clk" hwSignal="pin" hwResource="//@hwResources.26"/>
  <virtualSignals name="Card Detect_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_sdcd" hwSignal="pin" hwResource="//@hwResources.27"/>
  <virtualSignals name="Write Protect_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_sdwc" hwSignal="pin" hwResource="//@hwResources.28"/>
  <virtualSignals name="Reset_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_rst" hwSignal="pin" hwResource="//@hwResources.29"/>
  <virtualSignals name="Bus Power_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_bus_pwr" hwSignal="pin" hwResource="//@hwResources.30"/>
  <virtualSignals name="LED_signal" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_led" hwSignal="pin" hwResource="//@hwResources.31"/>
  <requiredApps URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/appres_spi_master" requiredAppName="SPI_MASTER" required="false"/>
  <requiredApps URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/appres_cmsis_rtos" requiredAppName="CMSIS_RTOS" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/appres_cpu_ctrl" requiredAppName="CPU_CTRL_XMC4" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CPU_CTRL_XMC4/v4_0_16/CPU_CTRL_XMC4_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/appres_systimer" requiredAppName="SYSTIMER" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../SYSTIMER/v4_1_16/SYSTIMER_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/appres_clock" requiredAppName="CLOCK_XMC4" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CLOCK_XMC4/v4_0_22/CLOCK_XMC4_0.app#/"/>
  </requiredApps>
  <hwResources name="SDMMC Host" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_sdmmc_host" resourceGroupUri="peripheral/sdmmc/*/host" mResGrpUri="peripheral/sdmmc/*/host">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/SDMMC/SDMMC_0.dd#//@provided.0"/>
  </hwResources>
  <hwResources name="SDMMC NVIC Node" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_cpu_nvic_interrupt_sdnode" resourceGroupUri="peripheral/cpu/0/nvic/interrupt/*" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CPU/CPU_0.dd#//@provided.14"/>
  </hwResources>
  <hwResources name="Data pin 0" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_0" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port4/Port4_4.dd#//@provided.0"/>
  </hwResources>
  <hwResources name="Data pin 1" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_1" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port1/Port1_1.dd#//@provided.0"/>
  </hwResources>
  <hwResources name="Data pin 2" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_2" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port1/Port1_1.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="Data pin 3" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_3" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port4/Port4_4.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="Data pin 4" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_4" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Data pin 5" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_5" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Data pin 6" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_6" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Data pin 7" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_data_7" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Command pin" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_cmd" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port3/Port3_3.dd#//@provided.0"/>
  </hwResources>
  <hwResources name="Clock pin" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_clk" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port3/Port3_3.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="Card Detect" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_sdcd" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Write Protect" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_sdwc" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Reset" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_rst" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Bus Power" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_bus_pwr" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="LED" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/hwres_port_pad_led" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Data pin 0" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_0" resourceGroupUri="devicepackage/0/85" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.9"/>
  </hwResources>
  <hwResources name="Data pin 1" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_1" resourceGroupUri="devicepackage/0/83" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.8"/>
  </hwResources>
  <hwResources name="Data pin 2" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_2" resourceGroupUri="devicepackage/0/82" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="Data pin 3" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_3" resourceGroupUri="devicepackage/0/84" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.7"/>
  </hwResources>
  <hwResources name="Data pin 4" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_4" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Data pin 5" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_5" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Data pin 6" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_6" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Data pin 7" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_data_7" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Command pin" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_cmd" resourceGroupUri="devicepackage/0/91" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.4"/>
  </hwResources>
  <hwResources name="Clock pin" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_clk" resourceGroupUri="devicepackage/0/90" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.5"/>
  </hwResources>
  <hwResources name="Card Detect" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_sdcd" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Write Protect" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_sdwc" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Reset" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_rst" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Bus Power" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_bus_pwr" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="LED" URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_hwres_port_pad_led" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_0_hw_o" systemDefined="true" sourceSignal="mmc_data_out_0" targetSignal="data_0_hw_o" srcVirtualSignal="//@virtualSignals.0" targetVirtualSignal="//@virtualSignals.30"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_1/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_1_hw_o" systemDefined="true" sourceSignal="mmc_data_out_1" targetSignal="data_1_hw_o" srcVirtualSignal="//@virtualSignals.1" targetVirtualSignal="//@virtualSignals.31"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_2/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_2_hw_o" systemDefined="true" sourceSignal="mmc_data_out_2" targetSignal="data_2_hw_o" srcVirtualSignal="//@virtualSignals.2" targetVirtualSignal="//@virtualSignals.32"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_3/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_3_hw_o" systemDefined="true" sourceSignal="mmc_data_out_3" targetSignal="data_3_hw_o" srcVirtualSignal="//@virtualSignals.3" targetVirtualSignal="//@virtualSignals.33"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_4/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_4_hw_o" systemDefined="true" sourceSignal="mmc_data_out_4" targetSignal="data_4_hw_o" required="false" srcVirtualSignal="//@virtualSignals.4" targetVirtualSignal="//@virtualSignals.34"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_5/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_5_hw_o" systemDefined="true" sourceSignal="mmc_data_out_5" targetSignal="data_5_hw_o" required="false" srcVirtualSignal="//@virtualSignals.5" targetVirtualSignal="//@virtualSignals.35"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_6/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_6_hw_o" systemDefined="true" sourceSignal="mmc_data_out_6" targetSignal="data_6_hw_o" required="false" srcVirtualSignal="//@virtualSignals.6" targetVirtualSignal="//@virtualSignals.36"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_data_out_7/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_data_7_hw_o" systemDefined="true" sourceSignal="mmc_data_out_7" targetSignal="data_7_hw_o" required="false" srcVirtualSignal="//@virtualSignals.7" targetVirtualSignal="//@virtualSignals.37"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_cmd_out/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_cmd_hw_o" systemDefined="true" sourceSignal="mmc_cmd_out" targetSignal="cmd_hw_o" srcVirtualSignal="//@virtualSignals.8" targetVirtualSignal="//@virtualSignals.38"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_clk_out/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_clk_hw_o" systemDefined="true" sourceSignal="mmc_clk_out" targetSignal="clk_hw_o" srcVirtualSignal="//@virtualSignals.9" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_interrupt/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_interrupt_sdmmc_host" systemDefined="true" sourceSignal="interrupt" targetSignal="sd_host_interrupt" srcVirtualSignal="//@virtualSignals.43" targetVirtualSignal="//@virtualSignals.44"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdcd/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_sdcd" systemDefined="true" sourceSignal="sdcd_pad" targetSignal="mmc_sdcd" required="false" srcVirtualSignal="//@virtualSignals.25" targetVirtualSignal="//@virtualSignals.10"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdwc/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_sdwc" systemDefined="true" sourceSignal="sdwc_pad" targetSignal="mmc_sdwc" required="false" srcVirtualSignal="//@virtualSignals.26" targetVirtualSignal="//@virtualSignals.11"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_rst/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_rst_hw_o" systemDefined="true" sourceSignal="mmc_reset" targetSignal="rst_hw_o" required="false" srcVirtualSignal="//@virtualSignals.12" targetVirtualSignal="//@virtualSignals.40"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_bus_pwr/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_bus_pwr_hw_o" systemDefined="true" sourceSignal="mmc_bus_power" targetSignal="bus_pwr_hw_o" required="false" srcVirtualSignal="//@virtualSignals.13" targetVirtualSignal="//@virtualSignals.41"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_led/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_port_led_hw_o" systemDefined="true" sourceSignal="mmc_led" targetSignal="led_hw_o" required="false" srcVirtualSignal="//@virtualSignals.14" targetVirtualSignal="//@virtualSignals.42"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_rst/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_rst" systemDefined="true" sourceSignal="mmc_reset" targetSignal="rst_pad" required="false" srcVirtualSignal="//@virtualSignals.12" targetVirtualSignal="//@virtualSignals.27"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_bus_pwr/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_bus_pwr" systemDefined="true" sourceSignal="mmc_bus_power" targetSignal="bus_pwr_pad" required="false" srcVirtualSignal="//@virtualSignals.13" targetVirtualSignal="//@virtualSignals.28"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_led/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_led" systemDefined="true" sourceSignal="mmc_led" targetSignal="led_pad" required="false" srcVirtualSignal="//@virtualSignals.14" targetVirtualSignal="//@virtualSignals.29"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_0" systemDefined="true" sourceSignal="data_0_pad" targetSignal="Data pin 0_signal" srcVirtualSignal="//@virtualSignals.15" targetVirtualSignal="//@virtualSignals.45"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_0" systemDefined="true" sourceSignal="Data pin 0_signal" targetSignal="data_0_pad" srcVirtualSignal="//@virtualSignals.45" targetVirtualSignal="//@virtualSignals.15"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_1/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_1" systemDefined="true" sourceSignal="data_1_pad" targetSignal="Data pin 1_signal" srcVirtualSignal="//@virtualSignals.16" targetVirtualSignal="//@virtualSignals.46"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_1/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_1" systemDefined="true" sourceSignal="Data pin 1_signal" targetSignal="data_1_pad" srcVirtualSignal="//@virtualSignals.46" targetVirtualSignal="//@virtualSignals.16"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_2/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_2" systemDefined="true" sourceSignal="data_2_pad" targetSignal="Data pin 2_signal" srcVirtualSignal="//@virtualSignals.17" targetVirtualSignal="//@virtualSignals.47"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_2/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_2" systemDefined="true" sourceSignal="Data pin 2_signal" targetSignal="data_2_pad" srcVirtualSignal="//@virtualSignals.47" targetVirtualSignal="//@virtualSignals.17"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_3/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_3" systemDefined="true" sourceSignal="data_3_pad" targetSignal="Data pin 3_signal" srcVirtualSignal="//@virtualSignals.18" targetVirtualSignal="//@virtualSignals.48"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_3/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_3" systemDefined="true" sourceSignal="Data pin 3_signal" targetSignal="data_3_pad" srcVirtualSignal="//@virtualSignals.48" targetVirtualSignal="//@virtualSignals.18"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_4/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_4" systemDefined="true" sourceSignal="data_4_pad" targetSignal="Data pin 4_signal" srcVirtualSignal="//@virtualSignals.19" targetVirtualSignal="//@virtualSignals.49"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_4/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_4" systemDefined="true" sourceSignal="Data pin 4_signal" targetSignal="data_4_pad" srcVirtualSignal="//@virtualSignals.49" targetVirtualSignal="//@virtualSignals.19"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_5/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_5" systemDefined="true" sourceSignal="data_5_pad" targetSignal="Data pin 5_signal" srcVirtualSignal="//@virtualSignals.20" targetVirtualSignal="//@virtualSignals.50"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_5/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_5" systemDefined="true" sourceSignal="Data pin 5_signal" targetSignal="data_5_pad" srcVirtualSignal="//@virtualSignals.50" targetVirtualSignal="//@virtualSignals.20"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_6/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_6" systemDefined="true" sourceSignal="data_6_pad" targetSignal="Data pin 6_signal" srcVirtualSignal="//@virtualSignals.21" targetVirtualSignal="//@virtualSignals.51"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_6/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_6" systemDefined="true" sourceSignal="Data pin 6_signal" targetSignal="data_6_pad" srcVirtualSignal="//@virtualSignals.51" targetVirtualSignal="//@virtualSignals.21"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_7/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_7" systemDefined="true" sourceSignal="data_7_pad" targetSignal="Data pin 7_signal" srcVirtualSignal="//@virtualSignals.22" targetVirtualSignal="//@virtualSignals.52"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_data_7/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_data_7" systemDefined="true" sourceSignal="Data pin 7_signal" targetSignal="data_7_pad" srcVirtualSignal="//@virtualSignals.52" targetVirtualSignal="//@virtualSignals.22"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_cmd/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_cmd" systemDefined="true" sourceSignal="cmd_pad" targetSignal="Command pin_signal" srcVirtualSignal="//@virtualSignals.23" targetVirtualSignal="//@virtualSignals.53"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_cmd/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_cmd" systemDefined="true" sourceSignal="Command pin_signal" targetSignal="cmd_pad" srcVirtualSignal="//@virtualSignals.53" targetVirtualSignal="//@virtualSignals.23"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_clk/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_clk" systemDefined="true" sourceSignal="clk_pad" targetSignal="Clock pin_signal" srcVirtualSignal="//@virtualSignals.24" targetVirtualSignal="//@virtualSignals.54"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_clk/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_clk" systemDefined="true" sourceSignal="Clock pin_signal" targetSignal="clk_pad" srcVirtualSignal="//@virtualSignals.54" targetVirtualSignal="//@virtualSignals.24"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdcd/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_sdcd" systemDefined="true" sourceSignal="sdcd_pad" targetSignal="Card Detect_signal" srcVirtualSignal="//@virtualSignals.25" targetVirtualSignal="//@virtualSignals.55"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_sdcd/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdcd" systemDefined="true" sourceSignal="Card Detect_signal" targetSignal="sdcd_pad" srcVirtualSignal="//@virtualSignals.55" targetVirtualSignal="//@virtualSignals.25"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdwc/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_sdwc" systemDefined="true" sourceSignal="sdwc_pad" targetSignal="Write Protect_signal" srcVirtualSignal="//@virtualSignals.26" targetVirtualSignal="//@virtualSignals.56"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_sdwc/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_sdwc" systemDefined="true" sourceSignal="Write Protect_signal" targetSignal="sdwc_pad" srcVirtualSignal="//@virtualSignals.56" targetVirtualSignal="//@virtualSignals.26"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_rst/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_rst" systemDefined="true" sourceSignal="rst_pad" targetSignal="Reset_signal" srcVirtualSignal="//@virtualSignals.27" targetVirtualSignal="//@virtualSignals.57"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_rst/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_rst" systemDefined="true" sourceSignal="Reset_signal" targetSignal="rst_pad" srcVirtualSignal="//@virtualSignals.57" targetVirtualSignal="//@virtualSignals.27"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_bus_pwr/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_bus_pwr" systemDefined="true" sourceSignal="bus_pwr_pad" targetSignal="Bus Power_signal" srcVirtualSignal="//@virtualSignals.28" targetVirtualSignal="//@virtualSignals.58"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_bus_pwr/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_bus_pwr" systemDefined="true" sourceSignal="Bus Power_signal" targetSignal="bus_pwr_pad" srcVirtualSignal="//@virtualSignals.58" targetVirtualSignal="//@virtualSignals.28"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_led/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_led" systemDefined="true" sourceSignal="led_pad" targetSignal="LED_signal" srcVirtualSignal="//@virtualSignals.29" targetVirtualSignal="//@virtualSignals.59"/>
  <connections URI="http://resources/4.0.26/app/SDMMC_BLOCK/0/http://resources/4.0.26/app/SDMMC_BLOCK/0/__pin_vs_sdmmc_block_pad_led/http://resources/4.0.26/app/SDMMC_BLOCK/0/vs_sdmmc_block_pad_led" systemDefined="true" sourceSignal="LED_signal" targetSignal="led_pad" srcVirtualSignal="//@virtualSignals.59" targetVirtualSignal="//@virtualSignals.29"/>
</ResourceModel:App>
